#!/usr/bin/env bash
#the file reader  
while IFS=: read -r username x user_id group_id comment home_directory shell
do
    echo "Username: $username"
    echo "User ID: $user_id"
    echo "Home Directory: $home_directory"
    echo "-----------------------------"
done < /etc/passwd
