#!/usr/bin/env bash
#the file reader  
while IFS=: read -r username _ user_id _  _ home_directory _
do
    echo "Username: $username"
    echo "User ID: $user_id"
    echo "Home Directory: $home_directory"
    echo "-----------------------------"
done < /etc/passwd
