#!/usr/bin/env bash
#displayin list formatt
for file in *; do
	if [[ "$file" != .* ]]; then
		name_after_dash=$(echo "$file" | cut -d'-' -f2-)
		        if [[ -n "$name_after_dash" ]]; then
            echo "$name_after_dash"
        fi
    fi
done
