#!/usr/bin/env bash
#whynoloveme
pid_file="/var/run/myscript.pid"
trap 'echo "I hate the kill command"; exit 0' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f "$pid_file"; exit 0' SIGQUIT
while true; do
  echo "To infinity and beyond indefinitely"
  sleep 2
done
