#!/usr/bin/env bash
output_file="/tmp/my_process"
while true; do
  echo "I am alive!" >> "$output_file"
  sleep 2
done
pid_file="/var/run/my_process.pid"
script_path="/path/to/manage_my_process.sh"

start_process() {
if [ -f "$pid_file" ]; then
    echo "manage_my_process is already running."
    exit 1
  fi
$script_path &
  echo $! > "$pid_file"
  echo "manage_my_process started"
}
stop_process() {
if [ -f "$pid_file" ]; then
    pid=$(cat "$pid_file")
    kill "$pid"
    rm -f "$pid_file"
    echo "manage_my_process stopped"
  else
    echo "No process is running"
  fi
}

restart_process() {
 stop_process
  start_process
  echo "manage_my_process restarted"
}
case "$1" in
  start)
    start_process
    ;;
  stop)
    stop_process
    ;;
  restart)
    restart_process
    ;;
  *)
    echo "Usage: manage_my_process {start|stop|restart}"
    ;;
esac
